### PR TITLE
Add support for a separate alpha image, both compressed and uncompressed

### PR DESCRIPTION
**Pull request by mbechard**

### CODE REVIEW

**Comment by bangnoise** [comment]
I'm happy with the RGTC part of this, am considering the uncompressed alpha and generating some comparisons.

**Comment by bangnoise** [comment]
This is now in the ycocg-alpha branch where I have edited the language a bit and will update the reference implementation before merging to master. Still considering uncompressed alpha. Comments welcome - especially if you think I've messed up the spec, I trimmed some of your changes.

**Comment by bangnoise** [comment]
Probably use HapA as identifier for alpha-only, and HapM for either Scaled YCoCg DXT5 + alpha (and if uncompressed and RGTC alpha are both allowed, they will share identifiers). Refer to alpha-only as "Hap Alpha-Only" and Y+a as "Hap Q Alpha". This will be documented when I address #4.

**Comment by bangnoise** [comment]
The spec will probably
- explicitly permit any single-texture format on its own inside a multi-image top-level section
- explicitly require that dimensions match (without padding) for multi-image sections with colour + alpha textures.

**Comment by mbechard** [comment]
That all makes sense to me.

**Comment by bangnoise** [comment]
I'm going to merge the ycocg-alpha soon - I've disallowed uncompressed alpha as the quality of RGTC1 seems good - it's similar or better than the quality of the rest of the codec formats. Happy to hear any arguments for its inclusion though.

**Pull request merged**
