### PR TITLE
Update information on Unity plugins for Hap playback

### PR DESCRIPTION
**Pull request by leavittx**

### CODE REVIEW

**Comment by bangnoise** [comment]
Why does this replace the RenderHeads one?

**Comment by leavittx** [comment]
Seems like AVPro Quicktime is deprecated! However seems there is a newer AVPro version exists. Should we replace AVPro Quicktime with AVPro and add the Demolition Media Hap as a second possibility?

**Comment by bangnoise** [comment]
That sounds good

**Comment by leavittx** [comment]
Done! Please accept the pull request!

**Pull request merged**
